# General Information
title: Jekyll Candor
author: Ted Martin
email: etmartinkazoo
description: > # this means to ignore newlines until "baseurl:"
  A Jekyll theme for semantic HTML, CSS, and JavaScript. Developers seeking clean, semantic HTML, framework free CSS, and vanilla JavaScript.
twitter_username: theokazoo
github_username: etmartinkazoo
# Build settings
url:
permalink: pretty
# SASS directory
sass:
    sass_dir: _sass
# Custom pages directory to keep root directory uncluttered
include: ['_pages']
# Markdown
markdown: kramdown
# GitHub flavored Markdown
input: GFM
# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
